[package]
name = "kodek"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = { version = "0.7.6", default-features = false }

[features]
default = ["std"]

std = ["alloc"]
alloc = []

# bytes = ["alloc", "dep:bytes"]
